version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    networks:
      - my_network
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:



