version: '3.9'

services:

  db:
    container_name: postgred
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  db_data:


networks:
  my_network:
    driver: bridge
