# version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=blog
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=12345678
  #   ports:
  #     - "3306:3306"
  #   command: --default-authentication-plugin=mysql_native_password
